apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-proxy-clusterrole.yaml
  - grafana-proxy-binding.yaml
  - auth-delegator-binding.yaml
  - grafana-sa-edit-rb.yaml
  - ds-token-secret.yaml
