---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-namespace-proxy
data:
  nginx.conf.template: |
    worker_processes 1;
    error_log /tmp/error.log warn;
    pid /tmp/nginx.pid;
    events { worker_connections 64; }
    http {
      server {
        listen 8080;
        location / {
          set $args "$args&namespace=NAMESPACE";
          proxy_set_header Authorization "Bearer SA_TOKEN_PLACEHOLDER";
          proxy_pass https://thanos-querier.openshift-monitoring.svc.cluster.local:9092;
          proxy_ssl_verify off;
        }
      }
    }
